"""
PostgreSQL relational seed script generator.
"""
import re
from pathlib import Path
from typing import Dict, List, Any
from canonforge.core.manifest import find_universe_root
from canonforge.engines.db.scanner import escape_sql

UNIVERSE_DIR = find_universe_root()
DATA_DIR = UNIVERSE_DIR / "data"

def export_all_sql_seeds(
    chars: List[Dict[str, Any]],
    bestiary: List[Dict[str, Any]],
    skills: List[Dict[str, Any]],
    equipment: List[Dict[str, Any]],
    items: List[Dict[str, Any]],
    recipes: List[Dict[str, Any]],
    quests: List[Dict[str, Any]],
    factions: List[Dict[str, Any]],
    places: List[Dict[str, Any]]
):
    """Generate complete PostgreSQL DDL and ON CONFLICT INSERT seeds for all domains."""
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    
    # 1. Characters Seed
    char_sql = [
        "-- CanonForge Lore -> Postgres Character Seed",
        "-- Auto-generated by sync_lore_to_gamedb.py (OKF v0.3 SSOT)",
        "BEGIN;",
        """CREATE TABLE IF NOT EXISTS characters (
    char_id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    house VARCHAR(64),
    faction VARCHAR(64),
    role VARCHAR(64),
    char_type VARCHAR(32) DEFAULT 'npc',
    status VARCHAR(32),
    birthday VARCHAR(32),
    birth_race VARCHAR(64) DEFAULT 'Human',
    biological_state VARCHAR(64) DEFAULT 'Pure Flesh',
    current_phase VARCHAR(64) DEFAULT 'Phase 1',
    level INT DEFAULT 1,
    strength INT DEFAULT 10,
    dexterity INT DEFAULT 10,
    vitality INT DEFAULT 10,
    willpower INT DEFAULT 10,
    force_stat INT DEFAULT 0,
    system_affinity INT DEFAULT 0
);"""
    ]
    for c in chars:
        cid = escape_sql(c.get("id"))
        name = escape_sql(c.get("title"))
        house = escape_sql(c.get("house", "Unassigned"))
        faction = escape_sql(c.get("faction", "Neutral"))
        role = escape_sql(c.get("role", "citizen"))
        ctype = escape_sql("hero" if ("status:hero" in c.get("labels", []) or "tag:hero" in c.get("labels", []) or "protagonist" in str(c.get("labels", []))) else ("boss" if "boss" in str(c.get("labels", [])) else "npc"))
        status = escape_sql(c.get("entity_status", "Alive"))
        bdate = escape_sql(c.get("birth_date"))
        brace = escape_sql(c.get("birth_race", c.get("species", c.get("race", "Human"))))
        biostate = escape_sql(c.get("biological_state", "Cyborg (The Forged)" if c.get("forged") else "Pure Flesh"))
        phase = escape_sql(c.get("current_phase", "Phase 1"))
        lvl = c.get("level", 1)
        st = c.get("strength", 10)
        dx = c.get("dexterity", 10)
        vt = c.get("vitality", 10)
        wl = c.get("willpower", 10)
        fc = c.get("force", 0)
        sy = c.get("system_affinity", 0)
        
        char_sql.append(
            f"INSERT INTO characters (char_id, name, house, faction, role, char_type, status, birthday, birth_race, biological_state, current_phase, level, strength, dexterity, vitality, willpower, force_stat, system_affinity) "
            f"VALUES ({cid}, {name}, {house}, {faction}, {role}, {ctype}, {status}, {bdate}, {brace}, {biostate}, {phase}, {lvl}, {st}, {dx}, {vt}, {wl}, {fc}, {sy}) "
            f"ON CONFLICT (char_id) DO UPDATE SET name = EXCLUDED.name, status = EXCLUDED.status, role = EXCLUDED.role, biological_state = EXCLUDED.biological_state, current_phase = EXCLUDED.current_phase, level = EXCLUDED.level;"
        )
    char_sql.append("COMMIT;\n")
    with open(DATA_DIR / "characters_seed.sql", "w", encoding="utf-8") as f:
        f.write("\n".join(char_sql))
        
    # 2. Monsters Seed & Loot Table
    monster_sql = [
        "-- CanonForge Lore -> Postgres Bestiary Seed & Loot Tables",
        "-- Auto-generated by sync_lore_to_gamedb.py (OKF v0.3 SSOT)",
        "BEGIN;",
        """CREATE TABLE IF NOT EXISTS monsters (
    monster_id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    classification VARCHAR(64),
    origin VARCHAR(64),
    rarity VARCHAR(32),
    element VARCHAR(32),
    aspect VARCHAR(32),
    base_hp INT DEFAULT 50,
    base_atk INT DEFAULT 10,
    primary_habitat VARCHAR(128),
    danger_rating INT DEFAULT 1,
    weaknesses TEXT DEFAULT '[]',
    immunities TEXT DEFAULT '[]'
);""",
        """CREATE TABLE IF NOT EXISTS monster_loot_drops (
    monster_id VARCHAR(64) REFERENCES monsters(monster_id),
    item_id VARCHAR(64),
    drop_chance NUMERIC(4, 3) DEFAULT 1.0,
    min_qty INT DEFAULT 1,
    max_qty INT DEFAULT 1,
    PRIMARY KEY (monster_id, item_id)
);"""
    ]
    for m in bestiary:
        mid = escape_sql(m.get("id"))
        name = escape_sql(m.get("title"))
        cls = escape_sql(m.get("classification", "mob"))
        orig = escape_sql(m.get("origin", "hearthspawn"))
        rar = escape_sql(m.get("rarity", "common"))
        el = escape_sql(m.get("element", "Dark"))
        asp = escape_sql(m.get("aspect", "Attack"))
        hp = m.get("base_hp", 50)
        atk = m.get("base_atk", 10)
        hab = escape_sql(m.get("primary_habitat", "The Maw"))
        dang = m.get("danger_rating", 1)
        weak_json = escape_sql(json.dumps(m.get("weaknesses", [])))
        imm_json = escape_sql(json.dumps(m.get("immunities", [])))
        
        monster_sql.append(
            f"INSERT INTO monsters (monster_id, name, classification, origin, rarity, element, aspect, base_hp, base_atk, primary_habitat, danger_rating, weaknesses, immunities) "
            f"VALUES ({mid}, {name}, {cls}, {orig}, {rar}, {el}, {asp}, {hp}, {atk}, {hab}, {dang}, {weak_json}, {imm_json}) "
            f"ON CONFLICT (monster_id) DO UPDATE SET name = EXCLUDED.name, base_hp = EXCLUDED.base_hp, base_atk = EXCLUDED.base_atk;"
        )
        for drop in m.get("signature_drops", []):
            did = escape_sql(drop)
            monster_sql.append(
                f"INSERT INTO monster_loot_drops (monster_id, item_id, drop_chance, min_qty, max_qty) "
                f"VALUES ({mid}, {did}, 1.0, 1, 1) "
                f"ON CONFLICT (monster_id, item_id) DO NOTHING;"
            )
    monster_sql.append("COMMIT;\n")
    with open(DATA_DIR / "monsters_seed.sql", "w", encoding="utf-8") as f:
        f.write("\n".join(monster_sql))
        
    # 3. Skills Seed
    skill_sql = [
        "-- CanonForge Lore -> Postgres Skills Seed",
        "-- Auto-generated by sync_lore_to_gamedb.py (OKF v0.3 SSOT)",
        "BEGIN;",
        """CREATE TABLE IF NOT EXISTS skills (
    skill_id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    job_path VARCHAR(64),
    skill_tier VARCHAR(16),
    skill_type VARCHAR(32),
    resource_pool VARCHAR(16),
    resource_cost INT DEFAULT 0,
    target_pattern VARCHAR(64),
    primary_effect VARCHAR(32) DEFAULT 'damage',
    effect_magnitude NUMERIC(5, 2) DEFAULT 1.0,
    resonance_capable BOOLEAN DEFAULT FALSE,
    polarity_affinity VARCHAR(32),
    legal_races VARCHAR(128) DEFAULT 'All'
);"""
    ]
    for s in skills:
        sid = escape_sql(s.get("id"))
        name = escape_sql(s.get("title"))
        job = escape_sql(s.get("job_path", "Universal"))
        tier = escape_sql(s.get("skill_tier", "C"))
        stype = escape_sql(s.get("skill_type", "Strike"))
        pool = escape_sql(s.get("resource_pool", "SP"))
        cost = s.get("resource_cost", 0)
        tgt = escape_sql(s.get("target", "single_enemy"))
        peffect = escape_sql(s.get("primary_effect", "damage"))
        mag = s.get("effect_magnitude", 1.0)
        res_cap = "TRUE" if s.get("resonance_capable") else "FALSE"
        pol = escape_sql(s.get("polarity_affinity", "Neutral"))
        lraces = escape_sql(", ".join(s.get("legal_races", ["All"])))
        
        skill_sql.append(
            f"INSERT INTO skills (skill_id, name, job_path, skill_tier, skill_type, resource_pool, resource_cost, target_pattern, primary_effect, effect_magnitude, resonance_capable, polarity_affinity, legal_races) "
            f"VALUES ({sid}, {name}, {job}, {tier}, {stype}, {pool}, {cost}, {tgt}, {peffect}, {mag}, {res_cap}, {pol}, {lraces}) "
            f"ON CONFLICT (skill_id) DO UPDATE SET name = EXCLUDED.name, resource_cost = EXCLUDED.resource_cost, effect_magnitude = EXCLUDED.effect_magnitude;"
        )
    skill_sql.append("COMMIT;\n")
    with open(DATA_DIR / "skills_seed.sql", "w", encoding="utf-8") as f:
        f.write("\n".join(skill_sql))
        
    # 4. Equipment Seed
    equip_sql = [
        "-- CanonForge Lore -> Postgres Equipment Seed",
        "-- Auto-generated by sync_lore_to_gamedb.py (OKF v0.3 SSOT)",
        "BEGIN;",
        """CREATE TABLE IF NOT EXISTS equipment (
    equip_id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    equipment_type VARCHAR(32),
    slot VARCHAR(32),
    rarity VARCHAR(32),
    job_class VARCHAR(64),
    terrestrial_element VARCHAR(32),
    master_polarity VARCHAR(32),
    item_power INT DEFAULT 100,
    base_atk INT DEFAULT 0,
    base_def INT DEFAULT 0,
    granted_skill VARCHAR(128)
);"""
    ]
    for eq in equipment:
        eid = escape_sql(eq.get("id"))
        name = escape_sql(eq.get("title"))
        etype = escape_sql(eq.get("equipment_type", "Weapon"))
        slot = escape_sql(eq.get("slot", "Mainhand"))
        rar = escape_sql(eq.get("rarity", "Common"))
        job = escape_sql(eq.get("job_class", "Warrior"))
        el = escape_sql(eq.get("terrestrial_element", "None"))
        pol = escape_sql(eq.get("master_polarity", "Neutral"))
        ip = eq.get("item_power", 100)
        atk = eq.get("base_atk", 0)
        df = eq.get("base_def", 0)
        skill = escape_sql(eq.get("granted_skill", ""))
        
        equip_sql.append(
            f"INSERT INTO equipment (equip_id, name, equipment_type, slot, rarity, job_class, terrestrial_element, master_polarity, item_power, base_atk, base_def, granted_skill) "
            f"VALUES ({eid}, {name}, {etype}, {slot}, {rar}, {job}, {el}, {pol}, {ip}, {atk}, {df}, {skill}) "
            f"ON CONFLICT (equip_id) DO UPDATE SET name = EXCLUDED.name, item_power = EXCLUDED.item_power, base_atk = EXCLUDED.base_atk;"
        )
    equip_sql.append("COMMIT;\n")
    with open(DATA_DIR / "equipment_seed.sql", "w", encoding="utf-8") as f:
        f.write("\n".join(equip_sql))

    # 5. Items Seed
    item_sql = [
        "-- CanonForge Lore -> Postgres Items & Crafting Seed",
        "-- Auto-generated by sync_lore_to_gamedb.py (OKF v0.3 SSOT)",
        "BEGIN;",
        """CREATE TABLE IF NOT EXISTS items (
    item_id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    item_kind VARCHAR(32),
    rarity VARCHAR(32),
    terrestrial_element VARCHAR(32),
    master_polarity VARCHAR(32),
    unit_value INT DEFAULT 0
);"""
    ]
    for it in items:
        iid = escape_sql(it.get("id"))
        name = escape_sql(it.get("title"))
        kind = escape_sql(it.get("item_kind", "material"))
        rar = escape_sql(it.get("rarity", "Common"))
        el = escape_sql(it.get("terrestrial_element", "None"))
        pol = escape_sql(it.get("master_polarity", "Neutral"))
        val = it.get("unit_value", 0)
        item_sql.append(
            f"INSERT INTO items (item_id, name, item_kind, rarity, terrestrial_element, master_polarity, unit_value) "
            f"VALUES ({iid}, {name}, {kind}, {rar}, {el}, {pol}, {val}) "
            f"ON CONFLICT (item_id) DO UPDATE SET name = EXCLUDED.name, unit_value = EXCLUDED.unit_value;"
        )
    item_sql.append("COMMIT;\n")
    with open(DATA_DIR / "items_seed.sql", "w", encoding="utf-8") as f:
        f.write("\n".join(item_sql))

    # 6. Recipes Seed
    recipe_sql = [
        "-- CanonForge Lore -> Postgres Recipes & Ingredients Seed",
        "-- Auto-generated by sync_lore_to_gamedb.py (OKF v0.3 SSOT)",
        "BEGIN;",
        """CREATE TABLE IF NOT EXISTS recipes (
    recipe_id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    category VARCHAR(32),
    required_station VARCHAR(64),
    crafting_time_seconds INT DEFAULT 0,
    output_item VARCHAR(64) NOT NULL,
    output_quantity INT DEFAULT 1,
    ingredients JSONB
);""",
        """CREATE TABLE IF NOT EXISTS recipe_ingredients (
    recipe_id VARCHAR(64) REFERENCES recipes(recipe_id),
    item_id VARCHAR(64),
    quantity INT NOT NULL DEFAULT 1,
    PRIMARY KEY (recipe_id, item_id)
);"""
    ]
    for r in recipes:
        rid = escape_sql(r.get("id"))
        name = escape_sql(r.get("title"))
        cat = escape_sql(r.get("category", "weapon"))
        sta = escape_sql(r.get("required_station", "Workbench"))
        ctime = r.get("crafting_time_seconds", 0)
        out_item = escape_sql(r.get("output_item"))
        out_qty = r.get("output_quantity", 1)
        ing_json = escape_sql(json.dumps(r.get("ingredients", [])))
        recipe_sql.append(
            f"INSERT INTO recipes (recipe_id, name, category, required_station, crafting_time_seconds, output_item, output_quantity, ingredients) "
            f"VALUES ({rid}, {name}, {cat}, {sta}, {ctime}, {out_item}, {out_qty}, {ing_json}) "
            f"ON CONFLICT (recipe_id) DO UPDATE SET name = EXCLUDED.name, crafting_time_seconds = EXCLUDED.crafting_time_seconds;"
        )
        for ing in r.get("ingredients", []):
            ing_id = escape_sql(ing.get("item_id") if isinstance(ing, dict) else ing)
            qty = ing.get("quantity", 1) if isinstance(ing, dict) else 1
            recipe_sql.append(
                f"INSERT INTO recipe_ingredients (recipe_id, item_id, quantity) "
                f"VALUES ({rid}, {ing_id}, {qty}) "
                f"ON CONFLICT (recipe_id, item_id) DO UPDATE SET quantity = EXCLUDED.quantity;"
            )
    recipe_sql.append("COMMIT;\n")
    with open(DATA_DIR / "recipes_seed.sql", "w", encoding="utf-8") as f:
        f.write("\n".join(recipe_sql))

    # 7. Quests Seed
    quest_sql = [
        "-- CanonForge Lore -> Postgres Quests Seed",
        "-- Auto-generated by sync_lore_to_gamedb.py (OKF v0.3 SSOT)",
        "BEGIN;",
        """CREATE TABLE IF NOT EXISTS quests (
    quest_id VARCHAR(64) PRIMARY KEY,
    title VARCHAR(128) NOT NULL,
    quest_tier VARCHAR(32),
    recommended_item_power INT DEFAULT 100,
    giver VARCHAR(128),
    location VARCHAR(128),
    dialogue_script VARCHAR(128)
);"""
    ]
    for q in quests:
        qid = escape_sql(q.get("id"))
        title = escape_sql(q.get("title"))
        tier = escape_sql(q.get("quest_tier", "main_story"))
        ip = q.get("recommended_item_power", 100)
        giver = escape_sql(q.get("giver", ""))
        loc = escape_sql(q.get("location", ""))
        script = escape_sql(q.get("dialogue_script", ""))
        quest_sql.append(
            f"INSERT INTO quests (quest_id, title, quest_tier, recommended_item_power, giver, location, dialogue_script) "
            f"VALUES ({qid}, {title}, {tier}, {ip}, {giver}, {loc}, {script}) "
            f"ON CONFLICT (quest_id) DO UPDATE SET title = EXCLUDED.title, recommended_item_power = EXCLUDED.recommended_item_power;"
        )
    quest_sql.append("COMMIT;\n")
    with open(DATA_DIR / "quests_seed.sql", "w", encoding="utf-8") as f:
        f.write("\n".join(quest_sql))
        
    # 8. World Seed (Factions & Places)
    world_sql = [
        "-- CanonForge Lore -> Postgres World (Factions & Places) Seed",
        "-- Auto-generated by sync_lore_to_gamedb.py (OKF v0.3 SSOT)",
        "BEGIN;",
        """CREATE TABLE IF NOT EXISTS factions (
    faction_id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    ideology TEXT,
    seat_of_power VARCHAR(128),
    leadership VARCHAR(128),
    currency VARCHAR(64),
    master_polarity VARCHAR(64),
    signature_unit VARCHAR(64)
);""",
        """CREATE TABLE IF NOT EXISTS places (
    place_id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    location_kind VARCHAR(64),
    danger_level INT DEFAULT 1,
    governing_faction VARCHAR(64),
    master_polarity VARCHAR(64),
    terrestrial_element VARCHAR(32)
);"""
    ]
    for fc in factions:
        fid = escape_sql(fc.get("id"))
        name = escape_sql(fc.get("title"))
        ideo = escape_sql(fc.get("ideology", ""))
        seat = escape_sql(fc.get("seat_of_power", ""))
        ldr = escape_sql(fc.get("leadership", ""))
        curr = escape_sql(fc.get("currency", ""))
        pol = escape_sql(fc.get("master_polarity", "Neutral"))
        unit = escape_sql(fc.get("signature_unit", ""))
        
        world_sql.append(
            f"INSERT INTO factions (faction_id, name, ideology, seat_of_power, leadership, currency, master_polarity, signature_unit) "
            f"VALUES ({fid}, {name}, {ideo}, {seat}, {ldr}, {curr}, {pol}, {unit}) "
            f"ON CONFLICT (faction_id) DO UPDATE SET name = EXCLUDED.name, ideology = EXCLUDED.ideology;"
        )
        
    for pl in places:
        pid = escape_sql(pl.get("id"))
        name = escape_sql(pl.get("title"))
        kind = escape_sql(pl.get("location_kind", "territory"))
        dang = pl.get("danger_level", 1)
        gov = escape_sql(pl.get("governing_faction", "Neutral"))
        pol = escape_sql(pl.get("master_polarity", "Neutral"))
        el = escape_sql(pl.get("terrestrial_element", "None"))
        
        world_sql.append(
            f"INSERT INTO places (place_id, name, location_kind, danger_level, governing_faction, master_polarity, terrestrial_element) "
            f"VALUES ({pid}, {name}, {kind}, {dang}, {gov}, {pol}, {el}) "
            f"ON CONFLICT (place_id) DO UPDATE SET name = EXCLUDED.name, danger_level = EXCLUDED.danger_level;"
        )
        
    world_sql.append("COMMIT;\n")
    with open(DATA_DIR / "world_seed.sql", "w", encoding="utf-8") as f:
        f.write("\n".join(world_sql))

    # 9. Views Seed (Combat Stats, Recipe Details, Monster Loot)
    views_sql = [
        "-- CanonForge Lore -> Canonical SQL Views",
        "-- Auto-generated by sync_lore_to_gamedb.py",
        """CREATE OR REPLACE VIEW v_character_combat_stats AS
SELECT
    char_id,
    name,
    faction,
    house,
    role,
    char_type,
    birth_race,
    biological_state,
    current_phase,
    level,
    strength,
    dexterity,
    vitality,
    willpower,
    force_stat,
    system_affinity,
    (80 + (vitality * 6) + (level * 5)) AS max_hp,
    (CASE WHEN biological_state LIKE '%Mechanical%' THEN 0 ELSE (force_stat * 4 + willpower * 3 + level * 2) END) AS max_fp,
    (40 + (vitality * 3) + (level * 2)) AS max_sp,
    (CASE WHEN biological_state LIKE '%Cyborg%' OR biological_state LIKE '%Mechanical%' THEN (50 + system_affinity * 4) ELSE 0 END) AS heat_capacity,
    (vitality * 2) AS base_phys_def,
    (willpower * 2) AS base_force_def,
    (strength * 2) AS base_phys_atk,
    (CASE WHEN biological_state LIKE '%Mechanical%' THEN 0 ELSE (force_stat * 2) END) AS base_force_atk
FROM characters;""",
        """CREATE OR REPLACE VIEW v_recipe_details AS
SELECT
    r.recipe_id,
    r.name AS recipe_name,
    r.category,
    r.required_station,
    r.crafting_time_seconds,
    r.output_item,
    r.output_quantity,
    ri.item_id AS ingredient_item_id,
    COALESCE(i.name, eq.name, ri.item_id) AS ingredient_name,
    ri.quantity AS required_quantity
FROM recipes r
JOIN recipe_ingredients ri ON r.recipe_id = ri.recipe_id
LEFT JOIN items i ON ri.item_id = i.item_id
LEFT JOIN equipment eq ON ri.item_id = eq.equip_id;""",
        """CREATE OR REPLACE VIEW v_monster_loot AS
SELECT
    m.monster_id,
    m.name AS monster_name,
    m.danger_rating,
    m.primary_habitat,
    d.item_id,
    COALESCE(i.name, d.item_id) AS item_name,
    d.drop_chance,
    d.min_qty,
    d.max_qty
FROM monsters m
JOIN monster_loot_drops d ON m.monster_id = d.monster_id
LEFT JOIN items i ON d.item_id = i.item_id;"""
    ]
    with open(DATA_DIR / "views_seed.sql", "w", encoding="utf-8") as f:
        f.write("\n\n".join(views_sql) + "\n")
        
    # 10. Master Runner Script (combines all)
    master_sql = [
        "-- CanonForge Lore Master Seed Runner",
        "-- Auto-generated by sync_lore_to_gamedb.py",
        "\\i characters_seed.sql",
        "\\i monsters_seed.sql",
        "\\i skills_seed.sql",
        "\\i equipment_seed.sql",
        "\\i items_seed.sql",
        "\\i recipes_seed.sql",
        "\\i quests_seed.sql",
        "\\i world_seed.sql",
        "\\i views_seed.sql"
    ]
    with open(DATA_DIR / "master_seed.sql", "w", encoding="utf-8") as f:
        f.write("\n".join(master_sql) + "\n")
        
    print(f"✅ Exported all PostgreSQL seed scripts (9 domains + views + master) to: {DATA_DIR}/")

# ==============================================================================
# MAIN CLI
# ==============================================================================

